apiVersion: v1
kind: Secret
metadata:
  name: linse-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "linse.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- .Values.config | nindent 4 }}
